source 'https://rubygems.org'

ruby '3.0.0'

gem 'rake'
gem 'test-unit'
gem 'rspec', '~> 3.10'
gem 'factory_bot', '~> 6.2'
gem 'faker', '~> 2.18'
gem 'active_record', '~> 7.0'
gem 'sqlite3', '~> 1.4'

group :development do
  gem 'rubocop', '~> 1.25'
  gem 'pry', '~> 0.14'
end

group :test do
  gem 'simplecov', '~> 0.21'
  gem 'webmock', '~> 3.14'
end