sonar.projectKey=BMillerCodes_sonarqube-examples_javascript
sonar.projectName=JavaScript Example
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.js.file.suffixes=.js
sonar.tests=tests