sonar.projectKey=BMillerCodes_sonarqube-examples_java
sonar.projectName=Java Example
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.binaries=target/classes
sonar.tests=src/test
sonar.junit.reportsPath=target/surefire-reports