name: SonarQube Scan - GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to retrieve history

      - name: Build
        run: echo "GitHub Actions workflows - static analysis"
        continue-on-error: true

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master # Using master for consistency
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         projectKey: BMillerCodes_sonarqube-examples_github-actions
         projectName: SonarQube GitHub Actions Example
         sources: github-actions/src/ # Adjusted source path
