name: SonarQube Scan - Swift

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to retrieve history

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Build
        run: swiftc -o src/main src/main.swift src/Helper.swift 2>&1 || true
        continue-on-error: true

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master # Using master for consistency
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         projectKey: BMillerCodes_sonarqube-examples_swift
         projectName: SonarQube Swift Example
         sources: swift/src/ # Adjusted source path