name: SonarQube Scan - XML

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to retrieve history

      - name: Build
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils && xmllint --noout xml/src/*.xml 2>&1 || true # Adjusted path and added apt-get for xmllint
        continue-on-error: true

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master # Using master for consistency
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         projectKey: BMillerCodes_sonarqube-examples_xml
         projectName: SonarQube XML Example
         sources: xml/src/ # Adjusted source path
